// 언어·기술별 공식 문서 링크 (검색형). kw: 검색 보조 키워드
export const DOC_LINKS = [
  // 웹 코어
  { name: 'JavaScript (MDN)', url: 'https://developer.mozilla.org/ko/docs/Web/JavaScript', kw: 'js 자바스크립트' },
  { name: 'TypeScript', url: 'https://www.typescriptlang.org/docs/', kw: 'ts 타입스크립트' },
  { name: 'HTML (MDN)', url: 'https://developer.mozilla.org/ko/docs/Web/HTML', kw: '에이치티엠엘' },
  { name: 'CSS (MDN)', url: 'https://developer.mozilla.org/ko/docs/Web/CSS', kw: '씨에스에스' },
  { name: 'Sass / SCSS', url: 'https://sass-lang.com/documentation/', kw: 'scss' },
  // 프로그래밍 언어
  { name: 'Python', url: 'https://docs.python.org/ko/3/', kw: 'py 파이썬' },
  { name: 'Java (JDK 21)', url: 'https://docs.oracle.com/en/java/javase/21/docs/api/', kw: '자바 jdk' },
  { name: 'Kotlin', url: 'https://kotlinlang.org/docs/home.html', kw: '코틀린' },
  { name: 'Swift', url: 'https://www.swift.org/documentation/', kw: '스위프트' },
  { name: 'C (cppreference)', url: 'https://en.cppreference.com/w/c', kw: '씨' },
  { name: 'C++ (cppreference)', url: 'https://en.cppreference.com/w/cpp', kw: 'cpp 씨쁠쁠' },
  { name: 'C# (.NET)', url: 'https://learn.microsoft.com/ko-kr/dotnet/csharp/', kw: 'csharp dotnet 씨샵' },
  { name: 'Go', url: 'https://go.dev/doc/', kw: 'golang 고' },
  { name: 'Rust', url: 'https://doc.rust-lang.org/book/', kw: '러스트' },
  { name: 'PHP', url: 'https://www.php.net/docs.php', kw: '피에이치피' },
  { name: 'Ruby', url: 'https://www.ruby-lang.org/ko/documentation/', kw: '루비' },
  { name: 'Dart', url: 'https://dart.dev/guides', kw: '다트' },
  { name: 'Scala', url: 'https://docs.scala-lang.org/', kw: '스칼라' },
  { name: 'Perl', url: 'https://perldoc.perl.org/', kw: '펄' },
  { name: 'Lua', url: 'https://www.lua.org/manual/5.4/', kw: '루아' },
  { name: 'R', url: 'https://cran.r-project.org/manuals.html', kw: '알' },
  { name: 'MATLAB', url: 'https://www.mathworks.com/help/matlab/', kw: '매트랩' },
  { name: 'Objective-C', url: 'https://developer.apple.com/documentation/objectivec', kw: '오브젝티브씨' },
  { name: 'Haskell', url: 'https://www.haskell.org/documentation/', kw: '하스켈' },
  { name: 'Elixir', url: 'https://elixir-lang.org/docs.html', kw: '엘릭서' },
  { name: 'Clojure', url: 'https://clojure.org/reference/documentation', kw: '클로저' },
  // 데이터 / DB
  { name: 'Oracle Database 23ai', url: 'https://docs.oracle.com/en/database/oracle/oracle-database/23/index.html', kw: '오라클 sql plsql' },
  { name: 'MySQL', url: 'https://dev.mysql.com/doc/', kw: '마이에스큐엘' },
  { name: 'PostgreSQL', url: 'https://www.postgresql.org/docs/', kw: 'postgres 포스트그레' },
  { name: 'MariaDB', url: 'https://mariadb.com/kb/en/documentation/', kw: '마리아디비' },
  { name: 'SQLite', url: 'https://www.sqlite.org/docs.html', kw: '에스큐엘라이트' },
  { name: 'SQL Server (T-SQL)', url: 'https://learn.microsoft.com/ko-kr/sql/', kw: 'mssql tsql' },
  { name: 'GraphQL', url: 'https://graphql.org/learn/', kw: '그래프큐엘' },
  // 마크업 / 데이터 포맷
  { name: 'Markdown Guide', url: 'https://www.markdownguide.org/', kw: 'md 마크다운' },
  { name: 'JSON', url: 'https://www.json.org/json-ko.html', kw: '제이슨' },
  { name: 'YAML', url: 'https://yaml.org/spec/', kw: '야믈' },
  { name: 'XML (MDN)', url: 'https://developer.mozilla.org/en-US/docs/Web/XML', kw: '엑스엠엘' },
  { name: 'Regex (regex101)', url: 'https://regex101.com/', kw: '정규식 정규표현식 regexp' },
  // 프레임워크 / 런타임
  { name: 'React', url: 'https://react.dev/', kw: '리액트' },
  { name: 'Vue', url: 'https://vuejs.org/guide/introduction.html', kw: '뷰' },
  { name: 'Angular', url: 'https://angular.dev/', kw: '앵귤러' },
  { name: 'Svelte', url: 'https://svelte.dev/docs', kw: '스벨트' },
  { name: 'Node.js', url: 'https://nodejs.org/docs/latest/api/', kw: '노드' },
  { name: 'Next.js', url: 'https://nextjs.org/docs', kw: '넥스트' },
  { name: 'Tailwind CSS', url: 'https://tailwindcss.com/docs', kw: '테일윈드' },
  { name: 'Flutter', url: 'https://docs.flutter.dev/', kw: '플러터' },
  // 셸 / 도구
  { name: 'Bash', url: 'https://www.gnu.org/software/bash/manual/', kw: 'shell 배시 셸' },
  { name: 'PowerShell', url: 'https://learn.microsoft.com/ko-kr/powershell/', kw: '파워셸' },
  { name: 'Git', url: 'https://git-scm.com/doc', kw: '깃' },
  { name: 'Docker', url: 'https://docs.docker.com/', kw: '도커' },
  { name: 'Kubernetes', url: 'https://kubernetes.io/ko/docs/home/', kw: 'k8s 쿠버네티스' },
]
