// Oracle 23ai 참고 템플릿 (Orange for Oracle 스타일 브라우저)
// 항목 선택 시 에디터 커서 위치에 code 가 삽입된다.
export const ORACLE_TEMPLATES = [
  {
    key: 'dml',
    title: 'DML 정보보기',
    items: [
      { name: 'SELECT (기본)', code: `SELECT col1, col2\n  FROM table_name\n WHERE condition\n ORDER BY col1;` },
      { name: 'SELECT (JOIN)', code: `SELECT a.id, a.name, b.dept_name\n  FROM emp a\n  JOIN dept b ON a.dept_id = b.id\n LEFT JOIN addr c ON c.emp_id = a.id\n WHERE a.active = 'Y';` },
      { name: 'SELECT (GROUP BY / HAVING)', code: `SELECT dept_id, COUNT(*) AS cnt, AVG(salary) AS avg_sal\n  FROM emp\n GROUP BY dept_id\nHAVING COUNT(*) >= 5\n ORDER BY cnt DESC;` },
      { name: 'SELECT (서브쿼리)', code: `SELECT *\n  FROM emp\n WHERE dept_id IN (SELECT id FROM dept WHERE loc = 'SEOUL');` },
      { name: 'SELECT (페이징 23ai)', code: `SELECT col1\n  FROM table_name\n ORDER BY col1\n OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY;` },
      { name: 'SELECT (FROM 없이 23ai)', code: `-- 23ai: FROM DUAL 생략 가능\nSELECT 1 + 1, SYSDATE;` },
      { name: 'INSERT', code: `INSERT INTO table_name (col1, col2)\nVALUES (value1, value2);` },
      { name: 'INSERT ... SELECT', code: `INSERT INTO target_table (col1, col2)\nSELECT col1, col2 FROM source_table WHERE condition;` },
      { name: 'INSERT ALL (다중 테이블)', code: `INSERT ALL\n  INTO t1 (id, v) VALUES (id, v)\n  INTO t2 (id, v) VALUES (id, v)\nSELECT id, v FROM source;` },
      { name: 'UPDATE', code: `UPDATE table_name\n   SET col1 = value1,\n       col2 = value2\n WHERE condition;` },
      { name: 'UPDATE (서브쿼리)', code: `UPDATE emp e\n   SET e.salary = (SELECT AVG(salary) FROM emp WHERE dept_id = e.dept_id)\n WHERE e.active = 'Y';` },
      { name: 'DELETE', code: `DELETE FROM table_name\n WHERE condition;` },
      { name: 'MERGE (UPSERT)', code: `MERGE INTO target t\nUSING source s\n   ON (t.id = s.id)\n WHEN MATCHED THEN\n   UPDATE SET t.val = s.val\n WHEN NOT MATCHED THEN\n   INSERT (id, val) VALUES (s.id, s.val);` },
      { name: 'RETURNING INTO', code: `INSERT INTO table_name (col1)\nVALUES (value1)\nRETURNING id INTO :out_id;` },
    ],
  },
  {
    key: 'plsql',
    title: 'PL/SQL 정보보기',
    items: [
      { name: 'Anonymous Block', code: `DECLARE\n  v_count NUMBER;\nBEGIN\n  SELECT COUNT(*) INTO v_count FROM table_name;\n  DBMS_OUTPUT.PUT_LINE('count = ' || v_count);\nEXCEPTION\n  WHEN OTHERS THEN\n    DBMS_OUTPUT.PUT_LINE(SQLERRM);\nEND;\n/` },
      { name: 'Procedure', code: `CREATE OR REPLACE PROCEDURE proc_name (\n  p_id   IN  NUMBER,\n  p_name OUT VARCHAR2\n) AS\nBEGIN\n  SELECT name INTO p_name FROM table_name WHERE id = p_id;\nEND proc_name;\n/` },
      { name: 'Function', code: `CREATE OR REPLACE FUNCTION fn_name (\n  p_id IN NUMBER\n) RETURN VARCHAR2 AS\n  v_name VARCHAR2(100);\nBEGIN\n  SELECT name INTO v_name FROM table_name WHERE id = p_id;\n  RETURN v_name;\nEND fn_name;\n/` },
      { name: 'Package (Spec + Body)', code: `CREATE OR REPLACE PACKAGE pkg_name AS\n  PROCEDURE do_work(p_id IN NUMBER);\nEND pkg_name;\n/\n\nCREATE OR REPLACE PACKAGE BODY pkg_name AS\n  PROCEDURE do_work(p_id IN NUMBER) IS\n  BEGIN\n    NULL;\n  END do_work;\nEND pkg_name;\n/` },
      { name: 'Cursor (Explicit)', code: `DECLARE\n  CURSOR c IS SELECT id, name FROM table_name;\n  v_rec c%ROWTYPE;\nBEGIN\n  OPEN c;\n  LOOP\n    FETCH c INTO v_rec;\n    EXIT WHEN c%NOTFOUND;\n    DBMS_OUTPUT.PUT_LINE(v_rec.name);\n  END LOOP;\n  CLOSE c;\nEND;\n/` },
      { name: 'REF Cursor', code: `DECLARE\n  TYPE rc IS REF CURSOR;\n  c   rc;\n  v   table_name%ROWTYPE;\nBEGIN\n  OPEN c FOR SELECT * FROM table_name WHERE id = 1;\n  FETCH c INTO v;\n  CLOSE c;\nEND;\n/` },
      { name: 'BULK COLLECT', code: `DECLARE\n  TYPE t_ids IS TABLE OF NUMBER;\n  l_ids t_ids;\nBEGIN\n  SELECT id BULK COLLECT INTO l_ids FROM table_name;\n  FORALL i IN 1 .. l_ids.COUNT\n    UPDATE table_name SET flag = 'Y' WHERE id = l_ids(i);\nEND;\n/` },
      { name: 'Exception (사용자 정의)', code: `DECLARE\n  e_custom EXCEPTION;\n  PRAGMA EXCEPTION_INIT(e_custom, -20001);\nBEGIN\n  RAISE_APPLICATION_ERROR(-20001, '사용자 오류');\nEXCEPTION\n  WHEN e_custom THEN\n    DBMS_OUTPUT.PUT_LINE('처리됨');\nEND;\n/` },
      { name: 'Trigger', code: `CREATE OR REPLACE TRIGGER trg_name\nBEFORE INSERT OR UPDATE ON table_name\nFOR EACH ROW\nBEGIN\n  :NEW.updated_at := SYSTIMESTAMP;\nEND;\n/` },
      { name: 'Associative Array', code: `DECLARE\n  TYPE map_t IS TABLE OF VARCHAR2(100) INDEX BY PLS_INTEGER;\n  m map_t;\nBEGIN\n  m(1) := 'a';\n  m(2) := 'b';\n  DBMS_OUTPUT.PUT_LINE(m(1));\nEND;\n/` },
    ],
  },
  {
    key: 'control',
    title: 'PL/SQL Control Structure 정보보기',
    items: [
      { name: 'IF / ELSIF / ELSE', code: `IF condition1 THEN\n  NULL;\nELSIF condition2 THEN\n  NULL;\nELSE\n  NULL;\nEND IF;` },
      { name: 'CASE (단순)', code: `CASE v_grade\n  WHEN 'A' THEN dbms_output.put_line('우수');\n  WHEN 'B' THEN dbms_output.put_line('보통');\n  ELSE dbms_output.put_line('기타');\nEND CASE;` },
      { name: 'CASE (검색형)', code: `CASE\n  WHEN v_score >= 90 THEN v_grade := 'A';\n  WHEN v_score >= 80 THEN v_grade := 'B';\n  ELSE v_grade := 'C';\nEND CASE;` },
      { name: 'Basic LOOP', code: `LOOP\n  EXIT WHEN condition;\nEND LOOP;` },
      { name: 'WHILE LOOP', code: `WHILE condition LOOP\n  NULL;\nEND LOOP;` },
      { name: 'FOR LOOP', code: `FOR i IN 1 .. 10 LOOP\n  DBMS_OUTPUT.PUT_LINE(i);\nEND LOOP;` },
      { name: 'FOR LOOP (REVERSE)', code: `FOR i IN REVERSE 1 .. 10 LOOP\n  DBMS_OUTPUT.PUT_LINE(i);\nEND LOOP;` },
      { name: 'Cursor FOR LOOP', code: `FOR rec IN (SELECT id, name FROM table_name) LOOP\n  DBMS_OUTPUT.PUT_LINE(rec.name);\nEND LOOP;` },
      { name: 'CONTINUE / 라벨', code: `<<outer>>\nFOR i IN 1 .. 10 LOOP\n  CONTINUE outer WHEN MOD(i, 2) = 0;\n  DBMS_OUTPUT.PUT_LINE(i);\nEND LOOP outer;` },
      { name: 'FORALL (Bulk DML)', code: `FORALL i IN 1 .. l_ids.COUNT\n  INSERT INTO table_name (id) VALUES (l_ids(i));` },
    ],
  },
  {
    key: 'pseudo',
    title: 'Pseudo Column 정보보기',
    items: [
      { name: 'ROWNUM', code: `SELECT * FROM (\n  SELECT col1 FROM table_name ORDER BY col1\n) WHERE ROWNUM <= 10;` },
      { name: 'ROWID', code: `SELECT ROWID, col1 FROM table_name WHERE condition;` },
      { name: 'LEVEL (계층 쿼리)', code: `SELECT LEVEL, col1\n  FROM table_name\n START WITH parent_id IS NULL\nCONNECT BY PRIOR id = parent_id;` },
      { name: 'CONNECT_BY_ROOT / PATH', code: `SELECT id,\n       CONNECT_BY_ROOT name AS root_name,\n       SYS_CONNECT_BY_PATH(name, '/') AS path\n  FROM org\nCONNECT BY PRIOR id = parent_id;` },
      { name: 'SYSDATE / SYSTIMESTAMP', code: `SELECT SYSDATE, SYSTIMESTAMP FROM DUAL;` },
      { name: 'Sequence NEXTVAL / CURRVAL', code: `SELECT seq_name.NEXTVAL FROM DUAL;\nSELECT seq_name.CURRVAL FROM DUAL;` },
      { name: 'SYS_GUID', code: `SELECT SYS_GUID() AS uuid FROM DUAL;` },
      { name: 'ORA_ROWSCN', code: `SELECT ORA_ROWSCN, col1 FROM table_name WHERE id = 1;` },
      { name: 'IDENTITY 컬럼 (23ai)', code: `CREATE TABLE t (\n  id   NUMBER GENERATED ALWAYS AS IDENTITY,\n  name VARCHAR2(100)\n);` },
    ],
  },
  {
    key: 'function',
    title: 'SQL Function 정보보기',
    items: [
      { name: '문자: SUBSTR / INSTR', code: `SELECT SUBSTR(col1, 1, 10) AS part,\n       INSTR(col1, ',') AS pos\n  FROM table_name;` },
      { name: '문자: REPLACE / TRIM / LPAD', code: `SELECT REPLACE(col1, 'a', 'b'),\n       TRIM(col1),\n       LPAD(col1, 10, '0')\n  FROM table_name;` },
      { name: '정규식: REGEXP_LIKE / SUBSTR', code: `SELECT col1\n  FROM table_name\n WHERE REGEXP_LIKE(col1, '^[0-9]{3}-[0-9]{4}$');\n\nSELECT REGEXP_SUBSTR('a,b,c', '[^,]+', 1, 2) FROM DUAL;` },
      { name: '숫자: ROUND / TRUNC / MOD', code: `SELECT ROUND(val, 2), TRUNC(val), MOD(val, 3) FROM table_name;` },
      { name: '날짜: TO_CHAR / TO_DATE', code: `SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS now,\n       TO_DATE('2026-06-21', 'YYYY-MM-DD') AS d\n  FROM DUAL;` },
      { name: '날짜: EXTRACT / MONTHS_BETWEEN', code: `SELECT EXTRACT(YEAR FROM SYSDATE) AS yr,\n       MONTHS_BETWEEN(SYSDATE, hire_date) AS months\n  FROM emp;` },
      { name: 'NULL: NVL / NVL2 / COALESCE', code: `SELECT NVL(col1, 0),\n       NVL2(col1, 'Y', 'N'),\n       COALESCE(col1, col2, 0)\n  FROM table_name;` },
      { name: '조건: DECODE / CASE', code: `SELECT DECODE(grade, 'A', '우수', 'B', '보통', '기타') AS label,\n       CASE WHEN salary > 5000 THEN 'HIGH' ELSE 'LOW' END AS band\n  FROM emp;` },
      { name: '비교: GREATEST / LEAST', code: `SELECT GREATEST(a, b, c), LEAST(a, b, c) FROM table_name;` },
      { name: '분석: ROW_NUMBER / RANK', code: `SELECT col1,\n       ROW_NUMBER() OVER (PARTITION BY grp ORDER BY col1) AS rn,\n       RANK()       OVER (PARTITION BY grp ORDER BY col1) AS rnk\n  FROM table_name;` },
      { name: '분석: LAG / LEAD', code: `SELECT col1,\n       LAG(col1)  OVER (ORDER BY dt) AS prev,\n       LEAD(col1) OVER (ORDER BY dt) AS next\n  FROM table_name;` },
      { name: '집계: LISTAGG', code: `SELECT grp,\n       LISTAGG(name, ', ') WITHIN GROUP (ORDER BY name) AS names\n  FROM table_name\n GROUP BY grp;` },
      { name: 'JSON (23ai)', code: `SELECT JSON_VALUE(data, '$.name') AS name,\n       JSON_OBJECT('id' VALUE id, 'name' VALUE name) AS jdoc\n  FROM table_name;` },
    ],
  },
  {
    key: 'hint',
    title: 'SQL Optimizer Hint 정보보기',
    items: [
      { name: 'INDEX / NO_INDEX', code: `SELECT /*+ INDEX(t idx_name) */ col1\n  FROM table_name t\n WHERE condition;\n\nSELECT /*+ NO_INDEX(t idx_name) */ col1 FROM table_name t;` },
      { name: 'FULL', code: `SELECT /*+ FULL(t) */ col1 FROM table_name t WHERE condition;` },
      { name: 'LEADING / USE_NL', code: `SELECT /*+ LEADING(a b) USE_NL(b) */ a.col1, b.col2\n  FROM a JOIN b ON a.id = b.a_id;` },
      { name: 'USE_HASH', code: `SELECT /*+ USE_HASH(a b) */ a.col1, b.col2\n  FROM a JOIN b ON a.id = b.a_id;` },
      { name: 'PARALLEL', code: `SELECT /*+ PARALLEL(t, 4) */ col1 FROM table_name t;` },
      { name: 'FIRST_ROWS / ORDERED', code: `SELECT /*+ FIRST_ROWS(10) */ col1 FROM table_name WHERE condition;\nSELECT /*+ ORDERED */ a.c1 FROM a, b WHERE a.id = b.a_id;` },
      { name: 'RESULT_CACHE', code: `SELECT /*+ RESULT_CACHE */ dept_id, COUNT(*)\n  FROM emp GROUP BY dept_id;` },
      { name: 'MATERIALIZE (WITH)', code: `WITH t AS (\n  SELECT /*+ MATERIALIZE */ id, v FROM big_table WHERE flag = 'Y'\n)\nSELECT * FROM t WHERE v > 100;` },
      { name: 'APPEND (직접 경로)', code: `INSERT /*+ APPEND */ INTO target_table\nSELECT * FROM source_table;` },
      { name: 'GATHER_PLAN_STATISTICS', code: `SELECT /*+ GATHER_PLAN_STATISTICS */ col1 FROM table_name WHERE condition;` },
    ],
  },
  {
    key: 'dict',
    title: 'Data Dictionary 정보보기',
    items: [
      { name: '★ 주요 사전 뷰 요약', code: `-- 접두어: USER_(내 소유) / ALL_(접근가능) / DBA_(전체, 권한필요) / V$_(동적성능)\n-- 객체:     USER_OBJECTS, USER_TABLES, USER_VIEWS, USER_SEQUENCES, USER_SYNONYMS\n-- 컬럼:     USER_TAB_COLUMNS, USER_COL_COMMENTS, USER_TAB_COMMENTS\n-- 제약/인덱스: USER_CONSTRAINTS, USER_CONS_COLUMNS, USER_INDEXES, USER_IND_COLUMNS\n-- 소스/의존: USER_SOURCE, USER_DEPENDENCIES, USER_TRIGGERS, USER_PROCEDURES\n-- 권한:     USER_TAB_PRIVS, USER_SYS_PRIVS, USER_ROLE_PRIVS, SESSION_PRIVS\n-- 저장공간: USER_SEGMENTS, USER_EXTENTS, USER_TS_QUOTAS\n-- 동적성능: V$SESSION, V$SQL, V$LOCK, V$PROCESS, V$DATABASE, V$INSTANCE\n-- 사전검색: DICTIONARY(=DICT), DICT_COLUMNS` },
      { name: '테이블 목록 (USER_TABLES)', code: `SELECT table_name, num_rows, last_analyzed\n  FROM user_tables\n ORDER BY table_name;` },
      { name: '컬럼 정보 (USER_TAB_COLUMNS)', code: `SELECT column_name, data_type, data_length, nullable, data_default\n  FROM user_tab_columns\n WHERE table_name = 'TABLE_NAME'\n ORDER BY column_id;` },
      { name: '인덱스 (USER_INDEXES / IND_COLUMNS)', code: `SELECT i.index_name, i.uniqueness, c.column_name, c.column_position\n  FROM user_indexes i\n  JOIN user_ind_columns c ON c.index_name = i.index_name\n WHERE i.table_name = 'TABLE_NAME'\n ORDER BY i.index_name, c.column_position;` },
      { name: '제약조건 (USER_CONSTRAINTS)', code: `SELECT c.constraint_name, c.constraint_type, cc.column_name\n  FROM user_constraints c\n  JOIN user_cons_columns cc ON cc.constraint_name = c.constraint_name\n WHERE c.table_name = 'TABLE_NAME'\n ORDER BY c.constraint_type, c.constraint_name;` },
      { name: 'PK / FK 관계', code: `SELECT a.table_name, a.constraint_name, a.r_constraint_name AS ref_pk\n  FROM user_constraints a\n WHERE a.constraint_type = 'R'   -- 외래키\n   AND a.table_name = 'TABLE_NAME';` },
      { name: '뷰 (USER_VIEWS)', code: `SELECT view_name, text\n  FROM user_views\n WHERE view_name = 'VIEW_NAME';` },
      { name: '시퀀스 (USER_SEQUENCES)', code: `SELECT sequence_name, min_value, max_value, increment_by, last_number\n  FROM user_sequences\n ORDER BY sequence_name;` },
      { name: '소스 보기 (USER_SOURCE)', code: `SELECT line, text\n  FROM user_source\n WHERE name = 'OBJECT_NAME'   -- 프로시저/함수/패키지\n   AND type = 'PACKAGE BODY'\n ORDER BY line;` },
      { name: '객체 목록 (USER_OBJECTS)', code: `SELECT object_name, object_type, status, last_ddl_time\n  FROM user_objects\n WHERE object_type IN ('TABLE','VIEW','PROCEDURE','FUNCTION','PACKAGE')\n ORDER BY object_type, object_name;` },
      { name: '무효 객체 (INVALID)', code: `SELECT object_name, object_type, status\n  FROM user_objects\n WHERE status = 'INVALID';` },
      { name: '종속성 (USER_DEPENDENCIES)', code: `SELECT name, type, referenced_name, referenced_type\n  FROM user_dependencies\n WHERE referenced_name = 'TABLE_NAME';` },
      { name: '코멘트 (테이블/컬럼)', code: `SELECT table_name, comments FROM user_tab_comments WHERE table_name = 'TABLE_NAME';\nSELECT column_name, comments FROM user_col_comments WHERE table_name = 'TABLE_NAME';` },
      { name: '권한 (USER_TAB_PRIVS)', code: `SELECT grantee, table_name, privilege, grantable\n  FROM user_tab_privs\n WHERE table_name = 'TABLE_NAME';\n\nSELECT * FROM session_privs;` },
      { name: '세그먼트 용량 (USER_SEGMENTS)', code: `SELECT segment_name, segment_type, bytes/1024/1024 AS mb\n  FROM user_segments\n ORDER BY bytes DESC;` },
      { name: '현재 세션 (V$SESSION)', code: `SELECT sid, serial#, username, status, machine, program, sql_id\n  FROM v$session\n WHERE username IS NOT NULL\n ORDER BY status;` },
      { name: '실행 중 SQL (V$SQL)', code: `SELECT sql_id, executions, elapsed_time, sql_text\n  FROM v$sql\n WHERE sql_text LIKE '%TABLE_NAME%'\n ORDER BY elapsed_time DESC FETCH FIRST 20 ROWS ONLY;` },
      { name: '딕셔너리 검색 (DICT)', code: `SELECT table_name, comments\n  FROM dictionary\n WHERE table_name LIKE 'USER_%'\n ORDER BY table_name;` },
      { name: '컬럼 메타 검색 (DICT_COLUMNS)', code: `SELECT table_name, column_name, comments\n  FROM dict_columns\n WHERE table_name = 'USER_TABLES';` },
    ],
  },
  {
    key: 'ddl',
    title: 'DDL 정보보기',
    items: [
      { name: 'CREATE TABLE (제약 포함)', code: `CREATE TABLE emp (\n  emp_id     NUMBER         GENERATED ALWAYS AS IDENTITY PRIMARY KEY,\n  emp_name   VARCHAR2(100)  NOT NULL,\n  dept_id    NUMBER,\n  salary     NUMBER(10, 2)  DEFAULT 0,\n  hire_date  DATE           DEFAULT SYSDATE,\n  active     CHAR(1)        DEFAULT 'Y' CHECK (active IN ('Y','N')),\n  CONSTRAINT fk_emp_dept FOREIGN KEY (dept_id) REFERENCES dept(dept_id),\n  CONSTRAINT uq_emp_name UNIQUE (emp_name)\n);` },
      { name: 'CREATE TABLE AS SELECT', code: `-- 구조 + 데이터 복사 (제약조건은 복사 안 됨)\nCREATE TABLE emp_backup AS\nSELECT * FROM emp WHERE hire_date >= DATE '2024-01-01';` },
      { name: 'ALTER TABLE — 컬럼 추가', code: `ALTER TABLE emp ADD (\n  email     VARCHAR2(200),\n  phone_no  VARCHAR2(20)\n);` },
      { name: 'ALTER TABLE — 컬럼 수정', code: `ALTER TABLE emp MODIFY (\n  emp_name  VARCHAR2(200) NOT NULL,\n  salary    NUMBER(12, 2)\n);` },
      { name: 'ALTER TABLE — 컬럼 삭제', code: `ALTER TABLE emp DROP COLUMN phone_no;` },
      { name: 'ALTER TABLE — 제약조건 추가/삭제', code: `-- 제약 추가\nALTER TABLE emp ADD CONSTRAINT chk_salary CHECK (salary >= 0);\n\n-- 제약 삭제\nALTER TABLE emp DROP CONSTRAINT chk_salary;\n\n-- 제약 비활성화/활성화\nALTER TABLE emp DISABLE CONSTRAINT fk_emp_dept;\nALTER TABLE emp ENABLE  CONSTRAINT fk_emp_dept;` },
      { name: 'CREATE INDEX', code: `-- 단일 컬럼 인덱스\nCREATE INDEX idx_emp_name ON emp(emp_name);\n\n-- 복합 인덱스\nCREATE INDEX idx_emp_dept_sal ON emp(dept_id, salary);\n\n-- 유니크 인덱스\nCREATE UNIQUE INDEX uq_emp_email ON emp(email);\n\n-- 함수 기반 인덱스\nCREATE INDEX idx_emp_upper_name ON emp(UPPER(emp_name));` },
      { name: 'CREATE VIEW', code: `CREATE OR REPLACE VIEW v_emp_dept AS\nSELECT e.emp_id, e.emp_name, e.salary, d.dept_name\n  FROM emp e\n  JOIN dept d ON d.dept_id = e.dept_id\n WHERE e.active = 'Y'\n WITH READ ONLY;` },
      { name: 'CREATE SEQUENCE', code: `CREATE SEQUENCE seq_emp_id\n  START WITH 1\n  INCREMENT BY 1\n  NOCACHE\n  NOCYCLE;` },
      { name: 'CREATE SYNONYM', code: `-- 공용 시노님 (DBA 권한 필요)\nCREATE PUBLIC SYNONYM emp FOR hr.emp;\n\n-- 개인 시노님\nCREATE SYNONYM my_emp FOR hr.emp;` },
      { name: 'DROP … IF EXISTS (23ai)', code: `-- 23ai: 존재할 때만 삭제 (오류 없음)\nDROP TABLE     IF EXISTS emp_temp;\nDROP INDEX     IF EXISTS idx_emp_name;\nDROP VIEW      IF EXISTS v_emp_dept;\nDROP SEQUENCE  IF EXISTS seq_emp_id;\nDROP SYNONYM   IF EXISTS my_emp;` },
      { name: 'TRUNCATE TABLE', code: `-- 모든 행 삭제 (롤백 불가, DDL)\nTRUNCATE TABLE emp_temp;` },
      { name: 'COMMENT ON (테이블/컬럼)', code: `COMMENT ON TABLE  emp IS '직원 마스터 테이블';\nCOMMENT ON COLUMN emp.emp_id   IS '직원 PK (자동 생성)';\nCOMMENT ON COLUMN emp.emp_name IS '직원 이름 (유니크)';` },
      { name: '23ai BOOLEAN 컬럼', code: `-- 23ai: BOOLEAN 네이티브 지원\nCREATE TABLE tasks (\n  task_id   NUMBER PRIMARY KEY,\n  task_name VARCHAR2(200),\n  is_done   BOOLEAN DEFAULT FALSE\n);\n\n-- DML\nINSERT INTO tasks VALUES (1, '보고서 작성', TRUE);\nSELECT task_name FROM tasks WHERE is_done = TRUE;` },
      { name: 'GENERATED IDENTITY 컬럼', code: `-- ALWAYS: 항상 자동 생성 (직접 입력 불가)\n-- BY DEFAULT: 값 미입력 시 자동 생성\nCREATE TABLE orders (\n  order_id  NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1000 INCREMENT BY 1),\n  order_dt  DATE DEFAULT SYSDATE\n);` },
    ],
  },
  {
    key: 'query',
    title: '고급 쿼리',
    items: [
      { name: 'WITH CTE (공통 테이블 표현식)', code: `WITH dept_avg AS (\n  SELECT dept_id, AVG(salary) AS avg_sal\n    FROM emp\n   GROUP BY dept_id\n)\nSELECT e.emp_name, e.salary, d.avg_sal\n  FROM emp e\n  JOIN dept_avg d ON d.dept_id = e.dept_id\n WHERE e.salary > d.avg_sal;` },
      { name: '재귀 CTE (계층 탐색)', code: `WITH RECURSIVE org AS (\n  -- 앵커: 최상위\n  SELECT emp_id, emp_name, mgr_id, 1 AS lvl\n    FROM emp WHERE mgr_id IS NULL\n  UNION ALL\n  -- 재귀: 자식\n  SELECT e.emp_id, e.emp_name, e.mgr_id, o.lvl + 1\n    FROM emp e\n    JOIN org o ON o.emp_id = e.mgr_id\n)\nSELECT lvl, emp_name FROM org ORDER BY lvl;` },
      { name: '계층질의 CONNECT BY', code: `SELECT LEVEL AS lvl,\n       LPAD(' ', (LEVEL - 1) * 2) || emp_name AS tree,\n       SYS_CONNECT_BY_PATH(emp_name, ' > ') AS path\n  FROM emp\n START WITH mgr_id IS NULL\nCONNECT BY PRIOR emp_id = mgr_id\n ORDER SIBLINGS BY emp_name;` },
      { name: 'PIVOT', code: `-- 행 → 열 전환\nSELECT *\n  FROM (\n    SELECT dept_id, job, salary FROM emp\n  )\n PIVOT (\n   SUM(salary)\n   FOR job IN ('CLERK' AS clerk, 'MANAGER' AS manager, 'ANALYST' AS analyst)\n );` },
      { name: 'UNPIVOT', code: `-- 열 → 행 전환\nSELECT dept_id, quarter, revenue\n  FROM sales_summary\n UNPIVOT (\n   revenue FOR quarter IN (q1, q2, q3, q4)\n );` },
      { name: '분석함수: SUM OVER / RATIO_TO_REPORT', code: `SELECT dept_id,\n       emp_name,\n       salary,\n       SUM(salary) OVER (PARTITION BY dept_id)          AS dept_total,\n       RATIO_TO_REPORT(salary) OVER (PARTITION BY dept_id) AS ratio\n  FROM emp;` },
      { name: '분석함수: NTILE / FIRST_VALUE / LAST_VALUE', code: `SELECT emp_name,\n       salary,\n       NTILE(4)     OVER (ORDER BY salary) AS quartile,\n       FIRST_VALUE(salary) OVER (ORDER BY salary\n         ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS min_sal,\n       LAST_VALUE(salary)  OVER (ORDER BY salary\n         ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS max_sal\n  FROM emp;` },
      { name: 'GROUPING SETS', code: `SELECT dept_id, job, SUM(salary) AS total\n  FROM emp\n GROUP BY GROUPING SETS (\n   (dept_id, job),\n   (dept_id),\n   (job),\n   ()\n );` },
      { name: 'ROLLUP / CUBE', code: `-- ROLLUP: 소계 + 총계\nSELECT dept_id, job, SUM(salary)\n  FROM emp GROUP BY ROLLUP (dept_id, job);\n\n-- CUBE: 모든 조합 소계\nSELECT dept_id, job, SUM(salary)\n  FROM emp GROUP BY CUBE (dept_id, job);` },
      { name: '집합 연산 (UNION / MINUS / INTERSECT)', code: `-- UNION: 중복 제거 합집합\nSELECT emp_id FROM emp_2023\nUNION\nSELECT emp_id FROM emp_2024;\n\n-- MINUS: 차집합 (Oracle 전용, 표준: EXCEPT)\nSELECT emp_id FROM emp_2023\nMINUS\nSELECT emp_id FROM emp_2024;\n\n-- INTERSECT: 교집합\nSELECT emp_id FROM emp_2023\nINTERSECT\nSELECT emp_id FROM emp_2024;` },
    ],
  },
  {
    key: 'txn',
    title: 'Transaction',
    items: [
      { name: 'COMMIT / ROLLBACK', code: `-- 변경 확정\nCOMMIT;\n\n-- 변경 취소\nROLLBACK;` },
      { name: 'SAVEPOINT', code: `SAVEPOINT sp1;\n\nUPDATE emp SET salary = salary * 1.1 WHERE dept_id = 10;\n\n-- sp1 시점으로 부분 롤백\nROLLBACK TO SAVEPOINT sp1;\n\nCOMMIT;` },
      { name: 'SELECT FOR UPDATE', code: `-- 해당 행 잠금 (다른 세션 수정 불가)\nSELECT emp_id, salary\n  FROM emp\n WHERE dept_id = 10\n   FOR UPDATE;\n\n-- SKIP LOCKED: 잠긴 행 건너뜀 (큐 처리 패턴)\nSELECT * FROM tasks\n WHERE status = 'PENDING'\n   FOR UPDATE SKIP LOCKED\n FETCH FIRST 10 ROWS ONLY;` },
      { name: 'SET TRANSACTION', code: `-- 격리 수준 설정 (트랜잭션 시작 전)\nSET TRANSACTION ISOLATION LEVEL SERIALIZABLE;\nSET TRANSACTION ISOLATION LEVEL READ COMMITTED; -- 기본값` },
    ],
  },
  {
    key: 'new23ai',
    title: 'Oracle 23ai 신기능',
    items: [
      { name: 'SELECT without FROM', code: `-- 23ai: DUAL 없이 값 조회 가능\nSELECT 1 + 1 AS result;\nSELECT SYSDATE, USER;\nSELECT SYS_GUID();` },
      { name: 'GROUP BY 컬럼 alias', code: `-- 23ai: GROUP BY에서 SELECT alias 사용 가능\nSELECT TRUNC(hire_date, 'MM') AS hire_month,\n       COUNT(*) AS cnt\n  FROM emp\n GROUP BY hire_month  -- alias 직접 사용\n ORDER BY hire_month;` },
      { name: 'Table Value Constructor (VALUES)', code: `-- 23ai: VALUES로 인라인 테이블 생성\nSELECT *\n  FROM (VALUES (1, 'A'), (2, 'B'), (3, 'C'))\n         AS t(id, code);\n\n-- INSERT 다중 행\nINSERT INTO dept (dept_id, dept_name)\nVALUES (10, 'HR'),\n       (20, 'IT'),\n       (30, 'SALES');` },
      { name: 'IF [NOT] EXISTS DDL (23ai)', code: `-- 23ai: 존재 여부 확인 없이 안전한 DDL\nCREATE TABLE IF NOT EXISTS emp_log (\n  log_id  NUMBER GENERATED ALWAYS AS IDENTITY,\n  msg     VARCHAR2(4000),\n  log_dt  DATE DEFAULT SYSDATE\n);\n\nDROP TABLE IF EXISTS emp_log;\nDROP INDEX IF EXISTS idx_emp_name;` },
      { name: 'BOOLEAN 타입 (23ai)', code: `-- 23ai: BOOLEAN 네이티브 지원 (PL/SQL 밖 SQL에서도 사용)\nCREATE TABLE feature_flags (\n  flag_name VARCHAR2(100) PRIMARY KEY,\n  is_active BOOLEAN DEFAULT FALSE NOT NULL\n);\n\nINSERT INTO feature_flags VALUES ('DARK_MODE', TRUE);\n\nSELECT flag_name\n  FROM feature_flags\n WHERE is_active IS TRUE;` },
      { name: 'SQL Domain (23ai)', code: `-- 23ai: 도메인 — 컬럼 공통 제약/기본값/포맷 재사용\nCREATE DOMAIN email_domain AS VARCHAR2(200)\n  CONSTRAINT chk_email CHECK (VALUE LIKE '%@%')\n  DISPLAY LOWER(VALUE);\n\nCREATE TABLE contacts (\n  contact_id  NUMBER PRIMARY KEY,\n  email       email_domain\n);` },
      { name: 'JSON Relational Duality View (23ai)', code: `-- 23ai: 관계형 테이블을 JSON API로 노출\nCREATE OR REPLACE JSON RELATIONAL DUALITY VIEW emp_dv AS\n  emp @INSERT @UPDATE @DELETE\n  {\n    empId:    emp_id,\n    empName:  emp_name,\n    salary:   salary,\n    dept: dept @INSERT\n    {\n      deptId:   dept_id,\n      deptName: dept_name\n    }\n  };\n\n-- JSON으로 조회\nSELECT data FROM emp_dv WHERE JSON_VALUE(data, '$.empId') = 1;` },
      { name: 'VECTOR 데이터타입 (23ai)', code: `-- 23ai: AI 임베딩 벡터 저장\nCREATE TABLE doc_embeddings (\n  doc_id    NUMBER PRIMARY KEY,\n  doc_text  CLOB,\n  embedding VECTOR(1536, FLOAT32)  -- OpenAI ada-002 차원\n);\n\n-- 벡터 삽입 (예: 파이썬 드라이버로 바인딩 또는 FROM_VECTOR)\nINSERT INTO doc_embeddings (doc_id, doc_text, embedding)\nVALUES (1, '샘플 문서', TO_VECTOR('[0.1, 0.2, 0.3]'));` },
      { name: '벡터 유사도 검색 (23ai)', code: `-- 23ai: 코사인 유사도 기준 상위 5개 검색\nSELECT doc_id, doc_text,\n       VECTOR_DISTANCE(embedding, :query_vec, COSINE) AS dist\n  FROM doc_embeddings\n ORDER BY dist ASC\n FETCH FIRST 5 ROWS ONLY;\n\n-- 또는 VECTOR_EMBEDDING + 내장 모델 사용 (ONNX 모델 로드 후)\n-- SELECT VECTOR_EMBEDDING(my_model USING doc_text AS data) FROM doc_embeddings;` },
      { name: '파티션 테이블 — RANGE / LIST / HASH', code: `-- RANGE 파티션 (날짜 기반)\nCREATE TABLE sales (\n  sale_id   NUMBER,\n  sale_date DATE,\n  amount    NUMBER\n)\nPARTITION BY RANGE (sale_date) (\n  PARTITION p2024 VALUES LESS THAN (DATE '2025-01-01'),\n  PARTITION p2025 VALUES LESS THAN (DATE '2026-01-01'),\n  PARTITION p_max VALUES LESS THAN (MAXVALUE)\n);\n\n-- INTERVAL 파티션 (자동 생성)\nCREATE TABLE sales_auto (\n  sale_id   NUMBER,\n  sale_date DATE\n)\nPARTITION BY RANGE (sale_date)\nINTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))\n(\n  PARTITION p_start VALUES LESS THAN (DATE '2024-01-01')\n);` },
    ],
  },
  {
    key: 'dictuse',
    title: '사전 활용 SQL (실무)',
    items: [
      { name: '테이블 DDL 추출 (DBMS_METADATA)', code: `SELECT DBMS_METADATA.GET_DDL('TABLE', 'EMP') FROM DUAL;\n-- 인덱스: GET_DDL('INDEX', 'IDX_EMP')\n-- 패키지: GET_DDL('PACKAGE', 'PKG_NAME')` },
      { name: '특정 컬럼명을 가진 테이블 찾기', code: `SELECT table_name, column_name, data_type\n  FROM user_tab_columns\n WHERE column_name LIKE '%EMP_ID%'\n ORDER BY table_name;` },
      { name: '소스에서 문자열 검색', code: `SELECT name, type, line, text\n  FROM user_source\n WHERE UPPER(text) LIKE '%COMMIT%'\n ORDER BY name, line;` },
      { name: '자식(참조) 테이블 찾기 (FK)', code: `SELECT c.table_name AS child_table, c.constraint_name\n  FROM user_constraints p\n  JOIN user_constraints c ON c.r_constraint_name = p.constraint_name\n WHERE p.table_name = 'DEPT'\n   AND p.constraint_type = 'P';` },
      { name: '인덱스 없는 FK 컬럼 (성능)', code: `SELECT cc.table_name, cc.constraint_name, cc.column_name\n  FROM user_cons_columns cc\n  JOIN user_constraints c\n    ON c.constraint_name = cc.constraint_name AND c.constraint_type = 'R'\n WHERE NOT EXISTS (\n   SELECT 1 FROM user_ind_columns ic\n    WHERE ic.table_name = cc.table_name\n      AND ic.column_name = cc.column_name\n );` },
      { name: 'INVALID 객체 재컴파일 스크립트', code: `SELECT 'ALTER ' || object_type || ' ' || object_name || ' COMPILE;' AS cmd\n  FROM user_objects\n WHERE status = 'INVALID'\n   AND object_type IN ('PROCEDURE','FUNCTION','PACKAGE','VIEW','TRIGGER');` },
      { name: '비활성 제약조건 조회', code: `SELECT table_name, constraint_name, constraint_type, status\n  FROM user_constraints\n WHERE status = 'DISABLED';` },
      { name: '통계 미수집 테이블', code: `SELECT table_name, num_rows, last_analyzed\n  FROM user_tables\n WHERE last_analyzed IS NULL\n    OR last_analyzed < SYSDATE - 7;\n-- 수집: EXEC DBMS_STATS.GATHER_TABLE_STATS(USER, 'EMP');` },
      { name: '용량 큰 객체 Top 20', code: `SELECT segment_name, segment_type, ROUND(bytes/1024/1024, 1) AS mb\n  FROM user_segments\n ORDER BY bytes DESC\n FETCH FIRST 20 ROWS ONLY;` },
      { name: '최근 변경된 객체', code: `SELECT object_name, object_type, last_ddl_time\n  FROM user_objects\n WHERE last_ddl_time > SYSDATE - 1\n ORDER BY last_ddl_time DESC;` },
      { name: '블로킹 세션 조회', code: `SELECT s.blocking_session, s.sid, s.serial#, s.username, s.event, s.sql_id\n  FROM v$session s\n WHERE s.blocking_session IS NOT NULL;` },
      { name: '세션 강제 종료 스크립트', code: `SELECT 'ALTER SYSTEM KILL SESSION ''' || sid || ',' || serial# || ''' IMMEDIATE;' AS cmd\n  FROM v$session\n WHERE username = 'APPUSER'\n   AND status = 'INACTIVE';` },
      { name: '컬럼 코멘트 일괄 생성', code: `SELECT 'COMMENT ON COLUMN ' || table_name || '.' || column_name ||\n       ' IS '''';'  AS cmd\n  FROM user_tab_columns\n WHERE table_name = 'EMP'\n ORDER BY column_id;` },
      { name: '권한 부여 현황', code: `SELECT grantee, table_name, privilege, grantable\n  FROM user_tab_privs\n WHERE owner = USER\n ORDER BY table_name;` },
    ],
  },
]
